03/05/2024 13:23:00 - Internal - Could not execute code stage because exception thrown by code stage: A column named 'name' already belongs to this DataTable.
03/05/2024 13:23:00 - Internal - Could not execute code stage because exception thrown by code stage: A column named 'name' already belongs to this DataTable.
03/05/2024 13:23:00 - Internal - Could not execute code stage because exception thrown by code stage: A column named 'name' already belongs to this DataTable.
